--
-- PostgreSQL database dump
--

\restrict oux2dAQ2dnQdN0zjz5MtbHye3bcUDIKBhfzoLCRxdkZxH6J3ZnGo1HdLwqv6lfO

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alt_servisler; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alt_servisler (
    id bigint NOT NULL,
    aciklama character varying(255),
    aktif boolean,
    baslik character varying(255),
    ikon_url character varying(255),
    sira integer
);


ALTER TABLE public.alt_servisler OWNER TO postgres;

--
-- Name: alt_servisler_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.alt_servisler ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alt_servisler_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ayarlar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ayarlar (
    id bigint NOT NULL,
    email character varying(255),
    ofis_de character varying(255),
    ofis_tr character varying(255),
    sosyal_instagram character varying(255),
    sosyal_linkedin character varying(255),
    sosyalx character varying(255)
);


ALTER TABLE public.ayarlar OWNER TO postgres;

--
-- Name: ayarlar_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ayarlar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ayarlar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crew; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.crew (
    id bigint NOT NULL,
    aciklama text,
    ad_soyad character varying(255),
    aktif boolean,
    github character varying(255),
    linkedin character varying(255),
    resim_url text,
    unvan character varying(255),
    detay text,
    diller character varying(255),
    instagram character varying(255),
    tiktok character varying(255),
    youtube character varying(255),
    sira integer
);


ALTER TABLE public.crew OWNER TO postgres;

--
-- Name: crew_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.crew ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crew_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: esports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.esports (
    id bigint NOT NULL,
    ad_soyad character varying(255) NOT NULL,
    unvan character varying(255),
    aciklama text,
    detay text,
    diller character varying(255),
    linkedin character varying(255),
    instagram character varying(255),
    youtube character varying(255),
    tiktok character varying(255),
    resim_url character varying(255),
    olusturma_tarihi timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    basarilar text,
    takimlar text,
    achievements_bg_url text,
    teams_bg_url text,
    takim text,
    team_logos text
);


ALTER TABLE public.esports OWNER TO postgres;

--
-- Name: esports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.esports_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.esports_id_seq OWNER TO postgres;

--
-- Name: esports_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.esports_id_seq OWNED BY public.esports.id;


--
-- Name: etkinlikler; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.etkinlikler (
    id bigint NOT NULL,
    aciklama character varying(500),
    aktif boolean,
    baslik character varying(255),
    detay text,
    olusturma_tarihi timestamp(6) without time zone,
    resim_url character varying(255),
    sira integer
);


ALTER TABLE public.etkinlikler OWNER TO postgres;

--
-- Name: etkinlikler_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.etkinlikler ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.etkinlikler_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: haberler; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.haberler (
    id bigint NOT NULL,
    aktif boolean,
    baslik character varying(255),
    detay text,
    icerik character varying(500),
    resim_url character varying(255),
    tarih date,
    sira integer
);


ALTER TABLE public.haberler OWNER TO postgres;

--
-- Name: haberler_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.haberler ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.haberler_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: influencers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.influencers (
    id bigint NOT NULL,
    ad_soyad character varying(255),
    unvan character varying(255),
    aciklama text,
    detay character varying(255),
    youtube_takipci character varying(255),
    twitter_takipci character varying(255),
    instagram_takipci character varying(255),
    instagram character varying(255),
    youtube character varying(255),
    twitter character varying(255),
    resim_url character varying(255)
);


ALTER TABLE public.influencers OWNER TO postgres;

--
-- Name: influencers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.influencers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.influencers_id_seq OWNER TO postgres;

--
-- Name: influencers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.influencers_id_seq OWNED BY public.influencers.id;


--
-- Name: kullanicilar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kullanicilar (
    id bigint NOT NULL,
    kullanici_adi character varying(255),
    rol character varying(255),
    sifre character varying(255)
);


ALTER TABLE public.kullanicilar OWNER TO postgres;

--
-- Name: kullanicilar_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kullanicilar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kullanicilar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.media (
    id bigint NOT NULL,
    aciklama character varying(255),
    baslik character varying(255),
    kategori character varying(255),
    resim_urls text,
    takim_logo_url text,
    thumbnail_url text,
    youtube_url text
);


ALTER TABLE public.media OWNER TO postgres;

--
-- Name: media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_thumbnails; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.media_thumbnails (
    id bigint NOT NULL,
    baslik character varying(255),
    aciklama character varying(255),
    kategori character varying(255),
    thumbnail_url text,
    afis_url text,
    youtube_url text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.media_thumbnails OWNER TO postgres;

--
-- Name: media_thumbnails_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.media_thumbnails_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.media_thumbnails_id_seq OWNER TO postgres;

--
-- Name: media_thumbnails_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.media_thumbnails_id_seq OWNED BY public.media_thumbnails.id;


--
-- Name: portfolio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portfolio (
    id bigint NOT NULL,
    image_url text,
    team character varying(255),
    team_logo_url text,
    logo character varying(255)
);


ALTER TABLE public.portfolio OWNER TO postgres;

--
-- Name: portfolio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portfolio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portfolio_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portfolio_images (
    id integer NOT NULL,
    portfolio_id integer,
    image_url text
);


ALTER TABLE public.portfolio_images OWNER TO postgres;

--
-- Name: portfolio_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.portfolio_images_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.portfolio_images_id_seq OWNER TO postgres;

--
-- Name: portfolio_images_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.portfolio_images_id_seq OWNED BY public.portfolio_images.id;


--
-- Name: servisler; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.servisler (
    id bigint NOT NULL,
    aktif boolean,
    baslik character varying(255),
    detay text,
    ozet character varying(255),
    resim_url character varying(255),
    sira integer
);


ALTER TABLE public.servisler OWNER TO postgres;

--
-- Name: servisler_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.servisler ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servisler_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shoots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shoots (
    id bigint NOT NULL,
    description character varying(1000),
    image_url character varying(255),
    title character varying(255)
);


ALTER TABLE public.shoots OWNER TO postgres;

--
-- Name: shoots_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shoots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shoots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sponsorlar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sponsorlar (
    id bigint NOT NULL,
    ad character varying(255),
    aktif boolean,
    logo_url character varying(255),
    sira integer
);


ALTER TABLE public.sponsorlar OWNER TO postgres;

--
-- Name: sponsorlar_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sponsorlar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sponsorlar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: videos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.videos (
    id bigint NOT NULL,
    description character varying(1000),
    thumbnail_url character varying(255),
    title character varying(255),
    video_url character varying(255)
);


ALTER TABLE public.videos OWNER TO postgres;

--
-- Name: videos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.videos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.videos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: esports id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.esports ALTER COLUMN id SET DEFAULT nextval('public.esports_id_seq'::regclass);


--
-- Name: influencers id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.influencers ALTER COLUMN id SET DEFAULT nextval('public.influencers_id_seq'::regclass);


--
-- Name: media_thumbnails id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media_thumbnails ALTER COLUMN id SET DEFAULT nextval('public.media_thumbnails_id_seq'::regclass);


--
-- Name: portfolio_images id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio_images ALTER COLUMN id SET DEFAULT nextval('public.portfolio_images_id_seq'::regclass);


--
-- Data for Name: alt_servisler; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.alt_servisler (id, aciklama, aktif, baslik, ikon_url, sira) FROM stdin;
1	Şirketinizin profesyonel imajını yansıtan web siteleri tasarlıyoruz.	t	Kurumsal Web Siteleri	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760384579/aimagency/genel/tpyd2blzdlx8nhrpqxpa.png	\N
2	Ürünlerinizi çevrimiçi dünyaya taşımak artık çok kolay.	t	'E-Ticaret Çözümleri	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760384616/aimagency/genel/mkacusawv9krserthq0j.png	\N
3	Kullanıcı dostu ve estetik mobil arayüzler tasarlıyoruz	t	Mobil UX/UI Tasarımı	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760385128/aimagency/genel/bnrwdcpir3xb7jom5vm5.png	\N
4	İşletmenizin verilerini anlamlı içgörülere dönüştürerek stratejik kararlar almanıza yardımcı oluyoruz. Raporlama, görselleştirme ve veri madenciliği çözümleri sunuyoruz.	t	Veri Analitiği	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760385264/aimagency/genel/pyr2byi4uay8z7jmvha0.png	\N
5	Markanızın sosyal medyada güçlü bir kimlik kazanması için içerik planlama, kampanya yönetimi ve takipçi etkileşimi stratejileri geliştiriyoruz.	t	Sosyal Medya Yönetimi	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760385349/aimagency/genel/danldzrcpsjnhhd8uudp.png	\N
6	Veri güvenliğiniz için sistem açıklarını analiz ediyor, tehditlere karşı koruma stratejileri ve ağ güvenliği çözümleri sunuyoruz.	t	Siber Güvenlik Danışmanlığı	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760385471/aimagency/genel/i3fjcne4e9ekrgzypysl.png	\N
\.


--
-- Data for Name: ayarlar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ayarlar (id, email, ofis_de, ofis_tr, sosyal_instagram, sosyal_linkedin, sosyalx) FROM stdin;
\.


--
-- Data for Name: crew; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.crew (id, aciklama, ad_soyad, aktif, github, linkedin, resim_url, unvan, detay, diller, instagram, tiktok, youtube, sira) FROM stdin;
10	Founder of ULF Esports, leading innovation and strategy in digital entertainment.	Gülce Yaman	t	\N	https://linkedin.com/in/gulceyaman	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760697669/aimagency/genel/yefrrqfmacf7ul7hsqjn.png	Founder	ULF ESPORTS\\nLorem Ipsum is simply dummy text of the printing and typesetting industry.\\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.\\n\\nLANGUAGES: 🇹🇷 🇬🇧 🇩🇪 🇫🇷\\n\\nSocial Media: Instagram | YouTube | TikTok	🇹🇷 🇬🇧 🇩🇪 🇫🇷	https://instagram.com/gulceyaman	https://tiktok.com/@ulfesports	https://youtube.com/@ulfesports	\N
11	CEO of ULF Esports, responsible for strategic growth and partnerships.	Barış Çolak	t	\N	https://linkedin.com/in/bariscolak	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760697684/aimagency/genel/dwyvxvtqnzlk3afpxhek.png	CEO	ULF ESPORTS\\nLorem Ipsum is simply dummy text of the printing and typesetting industry.\\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s...	🇹🇷 🇬🇧 🇩🇪 🇫🇷	https://instagram.com/bariscolak	https://tiktok.com/@ulfesports	https://youtube.com/@ulfesports	\N
12	Director of operations, ensuring smooth team coordination and daily workflow.	Toprak Akkın	t	\N	https://linkedin.com/in/toprakakkin	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760697709/aimagency/genel/fbwgb9jh9ih9ykopy2li.png	Operation Director	ULF ESPORTS\\nLorem Ipsum is simply dummy text of the printing and typesetting industry...	🇹🇷 🇬🇧 🇩🇪 🇫🇷	https://instagram.com/toprakakkin	https://tiktok.com/@ulfesports	https://youtube.com/@ulfesports	\N
13	Creative head of ULF Esports visual design and brand identity.	Mustafa Aziz Aslan	t	\N	https://linkedin.com/in/mustafaaslan	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760697739/aimagency/genel/sp4nkyu1j24jeew6uzpf.png	Art Director	ULF ESPORTS\\nLorem Ipsum is simply dummy text of the printing and typesetting industry...	🇹🇷 🇬🇧 🇩🇪 🇫🇷	https://instagram.com/mustafaaslan	https://tiktok.com/@ulfesports	https://youtube.com/@ulfesports	\N
14	Responsible for digital strategy and brand communication across platforms.	Tuğhan Canikligil	t	\N	https://linkedin.com/in/tughancanikligil	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760697760/aimagency/genel/oq3njt25sfisbnufx0yx.png	Social Media Director	ULF ESPORTS\\nLorem Ipsum is simply dummy text of the printing and typesetting industry...	🇹🇷 🇬🇧 🇩🇪 🇫🇷	https://instagram.com/tughancanikligil	https://tiktok.com/@ulfesports	https://youtube.com/@ulfesports	\N
15	Director of video production and post-processing for ULF Esports content.	Aykut Demir	t	\N	https://linkedin.com/in/aykutdemir	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760697782/aimagency/genel/mbof0872jgesddyzrfbj.png	Videographer	ULF ESPORTS\\nLorem Ipsum is simply dummy text of the printing and typesetting industry...	🇹🇷 🇬🇧 🇩🇪 🇫🇷	https://instagram.com/aykutdemir	https://tiktok.com/@ulfesports	https://youtube.com/@ulfesports	\N
16	Designer specializing in digital branding and esports visuals.	Osman Çalkuşu	t	\N	https://linkedin.com/in/osmancalkusu	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760697839/aimagency/genel/ectbzhpzeabjmsimsguk.png	Designer	ULF ESPORTS\\nLorem Ipsum is simply dummy text of the printing and typesetting industry...	🇹🇷 🇬🇧 🇩🇪 🇫🇷	https://instagram.com/osmancalkusu	https://tiktok.com/@ulfesports	https://youtube.com/@ulfesports	\N
17	UI/UX designer for interactive projects and web experiences.	Ali Eren Karakoyun	t	\N	https://linkedin.com/in/alierenkarakoyun	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760697863/aimagency/genel/df0r5mp07pjb0jquabdw.png	Designer	ULF ESPORTS\\nLorem Ipsum is simply dummy text of the printing and typesetting industry...	🇹🇷 🇬🇧 🇩🇪 🇫🇷	https://instagram.com/alierenkarakoyun	https://tiktok.com/@ulfesports	https://youtube.com/@ulfesports	\N
\.


--
-- Data for Name: esports; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.esports (id, ad_soyad, unvan, aciklama, detay, diller, linkedin, instagram, youtube, tiktok, resim_url, olusturma_tarihi, basarilar, takimlar, achievements_bg_url, teams_bg_url, takim, team_logos) FROM stdin;
4	Emir “Shadowx” Demirtaş	Valorant Entry Fragger	Saldırgan oyun tarzı ve refleksleriyle rakip takımlara nefes aldırmayan profesyonel Valorant oyuncusu.	Shadowx, ULF Esports Valorant takımında Entry Fragger rolünü üstleniyor.  \nRakip savunmaları kırma, agresif entry frag’ler alma ve takımı için alan açma konularında üst düzey bir performans sergiliyor.  \nGenellikle Jett veya Raze ajanlarını tercih eden Emir, birebir savaşlardaki başarısı ve reaksiyon hızındaki ustalığıyla tanınıyor.  \nTakım içindeki pozitif enerjisi ve oyun zekasıyla hem taktiksel hem de moral anlamında ekibin en önemli parçalarından biri.	\N	https://linkedin.com/in/emirdemirtas	https://instagram.com/shadowxvalorant	https://youtube.com/@shadowx	https://tiktok.com/@shadowxvalorant	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760828744/aimagency/genel/l7bupcfamyyhsrn0qlgt.png	2025-10-19 00:57:47.83246	ESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025\nESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025\nESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025\nESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025\nESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025\nESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025\nESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025\nESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025\nESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025\nESL Cologne 2025 Grand Final\nBlast Premier Fall 2025 Semi Final\nIEM Dallas 2025	\N			ULF Esports Valorant	["https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1761065449/aimagency/logos/xzaav2er438rekmua6gh.png","https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1761065449/aimagency/logos/ytnjhdgv8tfjhcropatt.png","https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1761065449/aimagency/logos/fok4rmlwszcr72zmhhby.png"]
3	Ece Kara	League of Legends Destek Oyuncusu	Takım uyumu ve pozisyon bilgisiyle tanınan destek oyuncusu.	• TCL 2023 Bahar Mevsimi - En İyi Destek Ödülü\\n• Uluslararası 5v5 Arena 2024 - 2. sıra\\n• 4 yıllık profesyonel MOBA deneyimi\\n\\nOynadığı takımlar: Aurora, ULF Esports\\n\\nLANGUAGES: 🇹🇷 🇬🇧 🇫🇷	🇹🇷 🇬🇧 🇫🇷	https://linkedin.com/in/ecekara	https://instagram.com/ecekaraofficia	https://youtube.com/@ecekara	https://tiktok.com/@ecekara	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760885717/aimagency/genel/hlkljzuu9tjpujesdtrt.png	2025-10-18 22:54:19.593851	TCL 2023 En İyi Destek, Uluslararası 5v5 Arena 2024 İkincisi	\N				
2	Mertcan Demir	Valorant Oyuncusu	Agresif oyun stili ve hızlı refleksleriyle tanınan profesyonel Valorant oyuncusu.	• VCT Türkiye 2024 - Şampiyon\\n• Red Bull Campus Clutch 2023 - Yarı Finalist\\n• FPS oyunlarında 5 yıllık tecrübe\\n\\nOynadığı takımlar: FireStorm, ULF Esports\\n\\nLANGUAGES: 🇹🇷 🇬🇧 🇩🇪	🇹🇷 🇬🇧 🇩🇪	https://linkedin.com/in/mertcandemir	https://instagram.com/mertcandemirr	https://youtube.com/@mertcandemir	https://tiktok.com/@mertcanfps	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760882993/aimagency/genel/zalbbut6firhm8nej2ll.png	2025-10-18 22:54:19.593851	VCT Türkiye 2024 Şampiyonu, Red Bull Campus Clutch 2023 Yarı Finalist	\N			sfsefsef	\N
1	Ahmet Yılmaz	CS:GO Takım Kaptanı	ULF Esports takım kaptanı, stratejik oyun zekâsı ve takım yönetimiyle tanınır.	• ESL Challenger Series 2023 - Finalist\\n• DreamHack Open 2022 - MVP\\n• 7 yıllık profesyonel FPS deneyimi\\n\\nOynadığı takımlar: Eternal Fire, Space Soldiers, ULF Esports\\n\\nLANGUAGES: 🇹🇷 🇬🇧	🇹🇷 🇬🇧	https://linkedin.com/in/ahmetyilmaz	https://instagram.com/ahmetyilmaz	https://youtube.com/@ulfesports	https://tiktok.com/@ulfesports	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760883085/aimagency/genel/wq8vsaeqztvyrbyxedtw.png	2025-10-18 22:54:19.593851	ESL Challenger Series 2023 - Finalist, DreamHack Open 2022 - MVP	\N				\N
5	Zeynep “Lunara” Kaya	League of Legends Mid Laner	Takım oyunundaki soğukkanlılığı, oyun okuma becerisi ve büyücü şampiyonlardaki ustalığıyla tanınan profesyonel oyuncu.	Lunara, ULF Esports kadın League of Legends takımının orta koridor oyuncusudur.  \nKontrol büyücüleri ve burst mage karakterlerde uzmanlaşmıştır.  \nÖzellikle Orianna, Syndra ve Ahri ile rakip takımlara oyun kazandıran hamleler yapmaktadır.  \nTakım savaşlarında pozisyon almadaki başarısı, rotasyon bilgisi ve soğukkanlı karar mekanizmasıyla öne çıkar.  \nOyun dışında takım koçluğuna destek veren, taktiksel analizlerle antrenman planlarını şekillendiren bir lider figürdür.	\N	https://linkedin.com/in/zeynepkaya	https://instagram.com/lunaraofficial	https://youtube.com/@lunaraLOL	https://tiktok.com/@lunara.lol	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760825442/aimagency/genel/s09perezojxxhoze9x6o.png	2025-10-19 00:57:53.149394	• TCL Kadınlar Ligi 2024 - En İyi Mid Laner Ödülü  \n• Uluslararası 5v5 Arena 2024 - 2. Sıra  \n• Dreamhack Women’s Cup 2023 - MVP  \n• 5 yıllık MOBA tecrübesi, 1200+ resmi maç performansı	\N	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760825420/aimagency/esports/w22ukxhheylinkcgatou.png	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760825431/aimagency/esports/snjzsm3ioo0eijin202d.png	ULF Esports League of Legends	\N
6	Berkay “IronFist” Karahan	Counter-Strike 2 IGL & Rifler	Tecrübeli liderlik anlayışı ve oyun içi stratejileriyle takımın beyni olarak görev alan efsanevi IGL.	IronFist, ULF Esports Counter-Strike 2 takımının oyun içi lideridir (IGL).  \nHarita rotasyonlarında stratejik zekâsı ve round başına planlama kabiliyetiyle tanınır.  \nBerkay, taktiksel oyun planları kurarken rakiplerin ekonomik durumuna göre round varyasyonları belirler ve takımını yönlendirir.  \nEk olarak rifler pozisyonunda yüksek isabet oranına sahip olması onu hem taktiksel hem mekanik açıdan güçlü kılar.  \nTakım arkadaşları tarafından “soğukkanlı kaptan” olarak bilinir, stresli anlarda bile sakinliğini korur.	\N	https://linkedin.com/in/berkaykarahan	https://instagram.com/ironfistcs	https://youtube.com/@ironfistplays	https://tiktok.com/@ironfist.gg	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760825123/aimagency/genel/x0wz7e1m4lcm1k9ma6s4.png	2025-10-19 00:57:57.786017	 ESL Challenger Katowice 2024 - Finalist  \n BLAST Premier Spring 2024 - Playoff Aşaması  \n IEM Dallas 2023 - Çeyrek Final  \n Türkiye CS Masters 2024 - Şampiyon  \n 8 yıllık profesyonel CS tecrübesi, 5000+ round liderliği	\N	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760825101/aimagency/esports/oikynbb52qaxwz0mbvxv.png	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760825108/aimagency/esports/roatq6rq0wk0kchkkaiz.png	ULF Esports Counter-Strike 2	["https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1761061520/aimagency/logos/a7qbqrqusvf2pe13nxyr.png"]
\.


--
-- Data for Name: etkinlikler; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.etkinlikler (id, aciklama, aktif, baslik, detay, olusturma_tarihi, resim_url, sira) FROM stdin;
1	Türkiye’nin en büyük oyun ve e-spor festivali başladı!	t	AIM Gaming Fest 2025	17355	2025-10-13 21:52:45.180342	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760381564/aimagency/genel/fnnle81wpepn8fjykp5x.jpg	\N
2	Yazılım dünyasının önde gelen isimleri Konya’da buluştu.	t	Tech Summit Konya 2025	17356	2025-10-13 21:54:12.816835	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760381651/aimagency/genel/xhfddy715laex5iqrxhs.jpg	\N
3	Yeni girişimciler fikirlerini yatırımcılara sundu.	t	StartUp Meet 2025	17357	2025-10-13 21:55:23.937664	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760381723/aimagency/genel/wccmtgcffp9asukd4xq8.jpg	\N
5	f34f34f3	t	4f34f34f34f	17384	2025-10-15 16:18:27.969338	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760534307/aimagency/genel/nd8hkawe5tvb2bm2tuf6.jpg	\N
\.


--
-- Data for Name: haberler; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.haberler (id, aktif, baslik, detay, icerik, resim_url, tarih, sira) FROM stdin;
1	t	Yeni Ofisimiz Açıldı!	17358	AIMAgency artık daha geniş bir çalışma alanına sahip!	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760382015/aimagency/genel/ar1cywyzwjrku1vh4nee.png	2025-10-13	\N
2	t	AIMAcademy Yaz Bootcamp Başlıyor	17359	Ücretsiz yazılım eğitim kampı kayıtları açıldı!	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760382113/aimagency/genel/gpvourhfjkny3uvpd5pk.png	2025-10-13	\N
3	t	Hackathon 2025 Tamamlandı	17360	48 saatlik yazılım maratonunda kazananlar belli oldu.	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760382184/aimagency/genel/pwh800wqvpsgluur49jx.png	2025-10-13	\N
4	t	AIMAgency, Google Partner Oldu	17361	AIMAgency, Google ile resmi iş ortaklığı anlaşmasını duyurdu	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760382599/aimagency/genel/bkdoqgkxr47tgl3lgbbf.png	2025-10-13	\N
5	t	AIMAgency, 2025 Yılında Avrupa’ya Açılıyor	17412	AIMAgency, Avrupa pazarına açılmak için ilk adımı attıdwdwdwedewdwedwededdwedwedwedewwdwedwedwedwedwedwedew	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760382702/aimagency/genel/vwxmmteijn7ofo9lryjd.png	2025-10-13	\N
\.


--
-- Data for Name: influencers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.influencers (id, ad_soyad, unvan, aciklama, detay, youtube_takipci, twitter_takipci, instagram_takipci, instagram, youtube, twitter, resim_url) FROM stdin;
11	Elif Kaya	Moda Influencerı	Elif, tarz sahibi kombinleri ve yaratıcı moda önerileriyle sosyal medyada geniş bir kitleye ilham verir.	\N	150K	65K	310K	https://www.instagram.com/elifkayastyle	https://www.youtube.com/@ElifKayaStyle	https://twitter.com/elifkayastyle	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1761090807/aimagency/genel/znswdkcw42pvotn2vvvo.jpg
3	Selin Yılmaz	Güzellik & Makyaj Vloggerı	Selin, moda ve güzellik üzerine enerjik içerikler üreten popüler bir vloggerdır.	Selin, dünya çapında gezdiği şehirleri vlog’lar ve blog içerikleriyle takipçilerine sunuyor. Otel, restoran ve yerel kültür deneyimlerine odaklanıyor.	245K	30K	210K	https://www.instagram.com/selinyilmaz	https://www.youtube.com/@SelinYilmaz	https://twitter.com/selinyilmaz	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760907927/aimagency/genel/ha0d4jl7uairx2fsfuv6.jpg
4	Mehmet Arslan	Teknoloji İçerik Üreticisi	Mehmet, teknoloji dünyasındaki gelişmeleri sade ve anlaşılır biçimde anlatan bir içerik üreticisidir.	Mehmet, spor salonuna gitmeden fit kalmanın yollarını anlatıyor. Takipçilerine motivasyon, diyet planı ve egzersiz programı sunuyor.	180K	95K	120K	https://www.instagram.com/mehmetarslann	https://www.youtube.com/@MehmetArslanTech	https://twitter.com/mehmetarslan	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760907942/aimagency/genel/zahnlwdlu0mbu7ltzjlq.jpg
5	Deniz Aksoy	Seyahat Bloggerı	Deniz, dünyayı keşfederek gezi rehberleri ve seyahat deneyimleri paylaşan bir maceraperesttir.	Deniz, güzellik markalarıyla çalışarak ürün tanıtımı yapıyor. Aynı zamanda cruelty-free ve vegan ürünleri destekliyor.	90K	40K	130K	https://www.instagram.com/denizaksoytravel	https://www.youtube.com/@DenizAksoyTravel	https://twitter.com/denizaksoy	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760907952/aimagency/genel/jkfi5ld51htginc2t4b5.jpg
2	Can Demir	E-Spor Yayıncısı	Can, e-spor turnuvalarını ve oyun dünyasındaki gelişmeleri enerjik yayınlarıyla paylaşan bir yayıncıdır.	Can, her hafta yeni çıkan teknolojik ürünleri inceleyen ve performans testleri yapan bir içerik üreticisi. Takipçilerine tarafsız yorumlar sunarak teknoloji alışverişlerinde rehberlik ediyor.	60K	85K	40K	https://www.instagram.com/candemirgg	https://www.youtube.com/@CanDemirr	https://twitter.com/candemirgg	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760907917/aimagency/genel/yqtopetruorab3bcntvq.jpg
6	Burak Şahin	Fitness & Sağlık Koçu	Burak, sağlıklı yaşam tarzı ve spor motivasyonu üzerine eğitici içerikler üreten bir antrenördür.	\N	40K	20K	70K	https://www.instagram.com/buraksahinfit	https://www.youtube.com/@BurakSahinFit	https://twitter.com/buraksahinfit	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760907965/aimagency/genel/gmgb7gbngodsftbz1dim.jpg
\.


--
-- Data for Name: kullanicilar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.kullanicilar (id, kullanici_adi, rol, sifre) FROM stdin;
2	sevkivolkantasbent@gmail.com	ADMIN	$2a$10$9H9lVo7IweLuw0DI6s0.M.YQwATdAPI8hfgOTvL742kupyyTZ.Fzu
\.


--
-- Data for Name: media; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.media (id, aciklama, baslik, kategori, resim_urls, takim_logo_url, thumbnail_url, youtube_url) FROM stdin;
\.


--
-- Data for Name: media_thumbnails; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.media_thumbnails (id, baslik, aciklama, kategori, thumbnail_url, afis_url, youtube_url, created_at) FROM stdin;
\.


--
-- Data for Name: portfolio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portfolio (id, image_url, team, team_logo_url, logo) FROM stdin;
22	https://res.cloudinary.com/dedurnabu/image/upload/v1761573029/aimagency/genel/fqxyvgurypdpka6bxdij.png,https://res.cloudinary.com/dedurnabu/image/upload/v1761573033/aimagency/genel/a5x4vhprlge4dmsmbw93.png,https://res.cloudinary.com/dedurnabu/image/upload/v1761573016/aimagency/genel/nxcw1o4f8ynffzmusboi.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573027/aimagency/genel/nexftgymgxay7dnfwzf0.png,https://res.cloudinary.com/dedurnabu/image/upload/v1761573020/aimagency/genel/ifgrx2l2ybvb70dqilh2.png,https://res.cloudinary.com/dedurnabu/image/upload/v1761573022/aimagency/genel/srtfvnvo4squexjbtx3c.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573023/aimagency/genel/fyy9gtkvpuff6sy9lf46.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573028/aimagency/genel/ym6yhksxkpfix0untrcn.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573030/aimagency/genel/ye5nlosti6jtmkmrlbsq.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573035/aimagency/genel/aataqyculrbjhaflzck7.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573040/aimagency/genel/smhmh0zoxmnvmobm5eot.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573034/aimagency/genel/yjv7qdwhls9goxei1vjn.jpg	volkan	\N	https://res.cloudinary.com/dedurnabu/image/upload/w_200,h_200,c_fit,q_100,f_auto/v1761573067/aimagency/logos/ubmfavjoed2iw1zbptgq.png
20	https://res.cloudinary.com/dedurnabu/image/upload/v1761573253/aimagency/genel/e6xzu54a5ijcukj2a7dw.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573256/aimagency/genel/jeurqrhazye4vyr1skzt.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573256/aimagency/genel/vlilauzfophqlorto36u.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573264/aimagency/genel/bst3a7vxc78ogj1eyutj.png,https://res.cloudinary.com/dedurnabu/image/upload/v1761573261/aimagency/genel/uwgi2rwxsojguhcoputn.png,https://res.cloudinary.com/dedurnabu/image/upload/v1761573251/aimagency/genel/ruviouxnbgzqbsb53ocz.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573266/aimagency/genel/ubwuhpycdom9ysb7tfey.png,https://res.cloudinary.com/dedurnabu/image/upload/v1761573259/aimagency/genel/mk6fvk5omrlwp5mi0ie8.png,https://res.cloudinary.com/dedurnabu/image/upload/v1761573263/aimagency/genel/r07tnsyzu102xsd97nme.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573263/aimagency/genel/ru6bzf2gazuluewy82an.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573262/aimagency/genel/qdydkgxu4gjqvzy41n1s.jpg,https://res.cloudinary.com/dedurnabu/image/upload/v1761573266/aimagency/genel/htfme6idvtosukim4abd.jpg	wedwedwedwe	\N	https://res.cloudinary.com/dedurnabu/image/upload/w_1600,h_1200,c_fit,q_100,f_auto/v1761569208/aimagency/logos/swaedxpen9zo2d5rmhqs.png
\.


--
-- Data for Name: portfolio_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portfolio_images (id, portfolio_id, image_url) FROM stdin;
\.


--
-- Data for Name: servisler; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.servisler (id, aktif, baslik, detay, ozet, resim_url, sira) FROM stdin;
2	t	UI / UX Tasarımı	17387	Kullanıcı dostu ve estetik tasarımlar.	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760540098/aimagency/genel/fhskaxqlann9f3li9rzl.png	\N
4	t	Media	17389	iOS ve Android platformları için performanslı uygulamalar.	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760387550/aimagency/genel/gjjgjvt8wjuwgnoun5ca.png	\N
1	t	Esports	17462	Competitive gaming and event management services provided by AIM Agency.	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760816630/aimagency/genel/j1bdejyum4lv8dchrgnf.jpg	\N
3	t	Influencers	17524	AI ile süreçlerinizi otomatikleştirin	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760979628/aimagency/genel/ktdqhhlpb4uuqj2vpwly.jpg	\N
\.


--
-- Data for Name: shoots; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shoots (id, description, image_url, title) FROM stdin;
4		https://res.cloudinary.com/dedurnabu/image/upload/v1761578010/aimagency/cekim/fffvaddlnzxeuxoztzws.png	ULF Esports x Eren7 Çekimleri
5		https://res.cloudinary.com/dedurnabu/image/upload/v1761578310/aimagency/cekim/dm5mxbm6vpgcbxqmfstu.png	ULF Esports x Eren7 Çekimleri 2
\.


--
-- Data for Name: sponsorlar; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sponsorlar (id, ad, aktif, logo_url, sira) FROM stdin;
1	yemekSepeti	t	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760381767/aimagency/genel/rhictn8f5ugklvecpt4u.png	\N
2	thy	t	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760381784/aimagency/genel/zfbghyquzqsxrayu21x9.png	\N
3	spotify	t	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760381805/aimagency/genel/n9zhdugwchxltrs4mx3w.png	\N
4	koç	t	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760381826/aimagency/genel/v7nz1c5gxnrc4pqgad8l.png	\N
5	Regnum	t	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760381877/aimagency/genel/jm3taf3b19eboxw7y85f.png	\N
6	papara	t	https://res.cloudinary.com/dedurnabu/image/upload/w_800,h_500,c_fit,q_auto:best,f_auto/v1760381891/aimagency/genel/t6j1hbcyu9cxkgl1sirz.png	\N
\.


--
-- Data for Name: videos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.videos (id, description, thumbnail_url, title, video_url) FROM stdin;
3	ULF Esports ile yapmis oldugumuz is birligi dogrultusunda Eren7 transferinin arkaplan sürecini izlemek için tikla!	https://img.youtube.com/vi/JS6JRBsKL6Q/maxresdefault.jpg	ULF Esports Eren7 Duyurusu	https://www.youtube.com/watch?v=JS6JRBsKL6Q
4	Bitmeyen Açlık Bizi Buraya Getirdi.	https://img.youtube.com/vi/hM_4JfNRzqA/maxresdefault.jpg	 SÜRÜYE HOŞ GELDİN EREN! 🔥 | PUBG MOBILE	https://www.youtube.com/watch?v=hM_4JfNRzqA
\.


--
-- Name: alt_servisler_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.alt_servisler_id_seq', 6, true);


--
-- Name: ayarlar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ayarlar_id_seq', 1, false);


--
-- Name: crew_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.crew_id_seq', 17, true);


--
-- Name: esports_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.esports_id_seq', 6, true);


--
-- Name: etkinlikler_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.etkinlikler_id_seq', 5, true);


--
-- Name: haberler_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.haberler_id_seq', 5, true);


--
-- Name: influencers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.influencers_id_seq', 12, true);


--
-- Name: kullanicilar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.kullanicilar_id_seq', 2, true);


--
-- Name: media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.media_id_seq', 1, false);


--
-- Name: media_thumbnails_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.media_thumbnails_id_seq', 1, false);


--
-- Name: portfolio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portfolio_id_seq', 22, true);


--
-- Name: portfolio_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portfolio_images_id_seq', 1, false);


--
-- Name: servisler_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.servisler_id_seq', 4, true);


--
-- Name: shoots_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shoots_id_seq', 5, true);


--
-- Name: sponsorlar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sponsorlar_id_seq', 6, true);


--
-- Name: videos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.videos_id_seq', 4, true);


--
-- Name: 17200..17524; Type: BLOB METADATA; Schema: -; Owner: postgres
--

SELECT pg_catalog.lo_create('17200');
SELECT pg_catalog.lo_create('17201');
SELECT pg_catalog.lo_create('17202');
SELECT pg_catalog.lo_create('17203');
SELECT pg_catalog.lo_create('17204');
SELECT pg_catalog.lo_create('17205');
SELECT pg_catalog.lo_create('17320');
SELECT pg_catalog.lo_create('17321');
SELECT pg_catalog.lo_create('17322');
SELECT pg_catalog.lo_create('17323');
SELECT pg_catalog.lo_create('17324');
SELECT pg_catalog.lo_create('17325');
SELECT pg_catalog.lo_create('17326');
SELECT pg_catalog.lo_create('17327');
SELECT pg_catalog.lo_create('17328');
SELECT pg_catalog.lo_create('17329');
SELECT pg_catalog.lo_create('17355');
SELECT pg_catalog.lo_create('17356');
SELECT pg_catalog.lo_create('17357');
SELECT pg_catalog.lo_create('17358');
SELECT pg_catalog.lo_create('17359');
SELECT pg_catalog.lo_create('17360');
SELECT pg_catalog.lo_create('17361');
SELECT pg_catalog.lo_create('17362');
SELECT pg_catalog.lo_create('17363');
SELECT pg_catalog.lo_create('17364');
SELECT pg_catalog.lo_create('17365');
SELECT pg_catalog.lo_create('17366');
SELECT pg_catalog.lo_create('17367');
SELECT pg_catalog.lo_create('17368');
SELECT pg_catalog.lo_create('17369');
SELECT pg_catalog.lo_create('17370');
SELECT pg_catalog.lo_create('17371');
SELECT pg_catalog.lo_create('17381');
SELECT pg_catalog.lo_create('17382');
SELECT pg_catalog.lo_create('17383');
SELECT pg_catalog.lo_create('17384');
SELECT pg_catalog.lo_create('17385');
SELECT pg_catalog.lo_create('17386');
SELECT pg_catalog.lo_create('17387');
SELECT pg_catalog.lo_create('17388');
SELECT pg_catalog.lo_create('17389');
SELECT pg_catalog.lo_create('17412');
SELECT pg_catalog.lo_create('17462');
SELECT pg_catalog.lo_create('17496');
SELECT pg_catalog.lo_create('17497');
SELECT pg_catalog.lo_create('17498');
SELECT pg_catalog.lo_create('17524');

ALTER LARGE OBJECT 17200 OWNER TO postgres;
ALTER LARGE OBJECT 17201 OWNER TO postgres;
ALTER LARGE OBJECT 17202 OWNER TO postgres;
ALTER LARGE OBJECT 17203 OWNER TO postgres;
ALTER LARGE OBJECT 17204 OWNER TO postgres;
ALTER LARGE OBJECT 17205 OWNER TO postgres;
ALTER LARGE OBJECT 17320 OWNER TO postgres;
ALTER LARGE OBJECT 17321 OWNER TO postgres;
ALTER LARGE OBJECT 17322 OWNER TO postgres;
ALTER LARGE OBJECT 17323 OWNER TO postgres;
ALTER LARGE OBJECT 17324 OWNER TO postgres;
ALTER LARGE OBJECT 17325 OWNER TO postgres;
ALTER LARGE OBJECT 17326 OWNER TO postgres;
ALTER LARGE OBJECT 17327 OWNER TO postgres;
ALTER LARGE OBJECT 17328 OWNER TO postgres;
ALTER LARGE OBJECT 17329 OWNER TO postgres;
ALTER LARGE OBJECT 17355 OWNER TO postgres;
ALTER LARGE OBJECT 17356 OWNER TO postgres;
ALTER LARGE OBJECT 17357 OWNER TO postgres;
ALTER LARGE OBJECT 17358 OWNER TO postgres;
ALTER LARGE OBJECT 17359 OWNER TO postgres;
ALTER LARGE OBJECT 17360 OWNER TO postgres;
ALTER LARGE OBJECT 17361 OWNER TO postgres;
ALTER LARGE OBJECT 17362 OWNER TO postgres;
ALTER LARGE OBJECT 17363 OWNER TO postgres;
ALTER LARGE OBJECT 17364 OWNER TO postgres;
ALTER LARGE OBJECT 17365 OWNER TO postgres;
ALTER LARGE OBJECT 17366 OWNER TO postgres;
ALTER LARGE OBJECT 17367 OWNER TO postgres;
ALTER LARGE OBJECT 17368 OWNER TO postgres;
ALTER LARGE OBJECT 17369 OWNER TO postgres;
ALTER LARGE OBJECT 17370 OWNER TO postgres;
ALTER LARGE OBJECT 17371 OWNER TO postgres;
ALTER LARGE OBJECT 17381 OWNER TO postgres;
ALTER LARGE OBJECT 17382 OWNER TO postgres;
ALTER LARGE OBJECT 17383 OWNER TO postgres;
ALTER LARGE OBJECT 17384 OWNER TO postgres;
ALTER LARGE OBJECT 17385 OWNER TO postgres;
ALTER LARGE OBJECT 17386 OWNER TO postgres;
ALTER LARGE OBJECT 17387 OWNER TO postgres;
ALTER LARGE OBJECT 17388 OWNER TO postgres;
ALTER LARGE OBJECT 17389 OWNER TO postgres;
ALTER LARGE OBJECT 17412 OWNER TO postgres;
ALTER LARGE OBJECT 17462 OWNER TO postgres;
ALTER LARGE OBJECT 17496 OWNER TO postgres;
ALTER LARGE OBJECT 17497 OWNER TO postgres;
ALTER LARGE OBJECT 17498 OWNER TO postgres;
ALTER LARGE OBJECT 17524 OWNER TO postgres;

--
-- Data for Name: 17200..17524; Type: BLOBS; Schema: -; Owner: postgres
--

BEGIN;

SELECT pg_catalog.lo_open('17200', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d2047616d696e67204665737420323032352c20332067c3bc6e20626f79756e63612031302e303030e2809964656e2066617a6c61206b6174c4b16cc4b16d63c4b179c4b12061c49fc4b1726c6164c4b12e205965726c69206f79756e2067656c69c59f7469726963696c6572207665206d61726b616c6172206269722061726179612067656c64692e205475726e7576616c61722c20636f73706c617920796172c4b1c59f6d616c6172c4b1207665206f79756e206c616e736d616e6c6172c4b1796c6120646f6c7520646f6c75206269722065746b696e6c696b206f6c64752e204b6174c4b16cc4b16d63c4b16c61722c2054c3bc726b697965e280996e696e2064c3b67274206269722079616ec4b16e64616e2067656c656e20652d73706f722074616bc4b16d6c6172c4b1796c612074616ec4b1c59f6d612066c4b172736174c4b12062756c64752e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17201', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d2047616d696e67204665737420323032352c20332067c3bc6e20626f79756e63612031302e303030e2809964656e2066617a6c61206b6174c4b16cc4b16d63c4b179c4b12061c49fc4b1726c6164c4b12e205965726c69206f79756e2067656c69c59f7469726963696c6572207665206d61726b616c6172206269722061726179612067656c64692e205475726e7576616c61722c20636f73706c617920796172c4b1c59f6d616c6172c4b1207665206f79756e206c616e736d616e6c6172c4b1796c6120646f6c7520646f6c75206269722065746b696e6c696b206f6c64752e204b6174c4b16cc4b16d63c4b16c61722c2054c3bc726b697965e280996e696e2064c3b67274206269722079616ec4b16e64616e2067656c656e20652d73706f722074616bc4b16d6c6172c4b1796c612074616ec4b1c59f6d612066c4b172736174c4b12062756c64752e44494f57454e4457454f49444f45574e44494f4e5745494f444e454f57494e444f4957454e44494f4e44494f4e57454f49444e494f57454e44494f4e44494e494f444e5745494f444e494f57454e444f4945574e44494e57454f49444e4f5749454e444f4945574e444f4957454f494e57444f494e494f4e44494f574e45494f444e5745494f4e44494f57454e444957454944494f4e4e44494f5744494e57454f49444e574f494e4457454f494e4f49444e4f5749454e4f4957454e444f4957454e444f49574e45494f4e5745494f4e44494f4e4557494f4e44494f574549444e4557494f4e444f49574e44494f574e445744494f4e57494f444e5745494e44494f57454e44494f4e444f49574e44');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17202', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d2047616d696e67204665737420323032352c20332067c3bc6e20626f79756e63612031302e303030e2809964656e2066617a6c61206b6174c4b16cc4b16d63c4b179c4b12061c49fc4b1726c6164c4b12e205965726c69206f79756e2067656c69c59f7469726963696c6572207665206d61726b616c6172206269722061726179612067656c64692e205475726e7576616c61722c20636f73706c617920796172c4b1c59f6d616c6172c4b1207665206f79756e206c616e736d616e6c6172c4b1796c6120646f6c7520646f6c75206269722065746b696e6c696b206f6c64752e204b6174c4b16cc4b16d63c4b16c61722c2054c3bc726b697965e280996e696e2064c3b67274206269722079616ec4b16e64616e2067656c656e20652d73706f722074616bc4b16d6c6172c4b1796c612074616ec4b1c59f6d612066c4b172736174c4b12062756c64752e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17203', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d20496e6e6f766174696f6e2053756d6d697420323032352c207961706179207a656bc3a264616e20626c6f6b7a696e6369722074656b6e6f6c6f6a696c6572696e65206b616461722067656c656365c49f696e207472656e646c6572696e6920656c6520616c616e20332067c3bc6e6cc3bc6b206269722065746b696e6c696b7469722e203530e2809964656e2066617a6c61206b6f6e75c59f6d6163c4b12c2032303030e28099696e20c3bc7a6572696e6465206b6174c4b16cc4b16d63c4b1207665206f6e6c617263612074656b6e6f6c6f6a692067697269c59f696d69206269722061726179612067656c64692e2042752079c4b16c20c3b67a656c6c696b6c65207961706179207a656bc3a22064657374656b6c6920736176756e6d612073697374656d6c657269207665206f746f6e6f6d20726f626f746c617220c3b66e6520c3a7c4b16b74c4b12e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17204', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d204372656174697665204d65657475702c2067726166696b207461736172c4b16d63c4b16c61722c2066696c6d20796170c4b16d63c4b16c6172c4b12c206dc3bc7a697379656e6c65722076652079617ac4b16cc4b16d2067656c69c59f7469726963696c657269206269722061726179612067657469726572656b206f7274616b2070726f6a656c6572696e2074656d656c6c6572696e6920617474c4b12e2045746b696e6c696b20626f79756e6361207961726174c4b163c4b12064c3bcc59fc3bc6e6d65206174c3b66c79656c6572692c20706f7274666f6c696f2073756e756d6c6172c4b1207665206d656e746f726c756b207365616e736c6172c4b12064c3bc7a656e6c656e64692e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17205', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d20496e6e6f766174696f6e2053756d6d697420323032352c207961706179207a656bc3a264616e20626c6f6b7a696e6369722074656b6e6f6c6f6a696c6572696e65206b616461722067656c656365c49f696e207472656e646c6572696e6920656c6520616c616e20332067c3bc6e6cc3bc6b206269722065746b696e6c696b7469722e203530e2809964656e2066617a6c61206b6f6e75c59f6d6163c4b12c2032303030e28099696e20c3bc7a6572696e6465206b6174c4b16cc4b16d63c4b1207665206f6e6c617263612074656b6e6f6c6f6a692067697269c59f696d69206269722061726179612067656c64692e2042752079c4b16c20c3b67a656c6c696b6c65207961706179207a656bc3a22064657374656b6c6920736176756e6d612073697374656d6c657269207665206f746f6e6f6d20726f626f746c617220c3b66e6520c3a7c4b16b74c4b12e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17320', 131072);
SELECT pg_catalog.lowrite(0, '\x4d6f6465726e20c3a7616cc4b1c59f6d6120616c616e6c6172c4b12c20746f706c616e74c4b1206f64616c6172c4b12076652064696e6c656e6d652062c3b66cc3bc6d6c657269796c6520646f6e6174c4b16c616e2079656e69206d65726b657a2c20c59f69726b6574696e2062c3bc79c3bc6d652076697a796f6e756e756e2062697220706172c3a76173c4b1206f6c6172616b2068697a6d6574652061c3a7c4b16c64c4b12e2041c3a7c4b16cc4b1c59f74612074c3bc6d20656b6970206269722061726179612067656c6572656b206b75746c616d612079617074c4b12e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17321', 131072);
SELECT pg_catalog.lowrite(0, '\x4d6f6465726e20c3a7616cc4b1c59f6d6120616c616e6c6172c4b12c20746f706c616e74c4b1206f64616c6172c4b12076652064696e6c656e6d652062c3b66cc3bc6d6c657269796c6520646f6e6174c4b16c616e2079656e69206d65726b657a2c20c59f69726b6574696e2062c3bc79c3bc6d652076697a796f6e756e756e2062697220706172c3a76173c4b1206f6c6172616b2068697a6d6574652061c3a7c4b16c64c4b12e2041c3a7c4b16cc4b1c59f74612074c3bc6d20656b6970206269722061726179612067656c6572656b206b75746c616d612079617074c4b12e7764c4b16f7765c4b16f646ec4b16f77656e64c4b16f6e6577c4b16f646e6fc4b165776e646fc4b165776e64c4b16f77656e64c4b16f6e7765646e6577c4b1646e6fc4b16e64c4b16f6e64c4b16f77656e64c4b16f77656e64c4b16f6e7765c4b16f646e7765c4b16f646e7765c4b16f6e64c4b16f65776e64c4b16f77656e64c4b16f77656e646fc4b177656e646fc4b16e646fc4b177656e64c4b16f77656e64c4b16f776e646fc4b1776e646fc4b1776e656f64c4b16e7765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17322', 131072);
SELECT pg_catalog.lowrite(0, '\x4d6f6465726e20c3a7616cc4b1c59f6d6120616c616e6c6172c4b12c20746f706c616e74c4b1206f64616c6172c4b12076652064696e6c656e6d652062c3b66cc3bc6d6c657269796c6520646f6e6174c4b16c616e2079656e69206d65726b657a2c20c59f69726b6574696e2062c3bc79c3bc6d652076697a796f6e756e756e2062697220706172c3a76173c4b1206f6c6172616b2068697a6d6574652061c3a7c4b16c64c4b12e2041c3a7c4b16cc4b1c59f74612074c3bc6d20656b6970206269722061726179612067656c6572656b206b75746c616d612079617074c4b12e27');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17323', 131072);
SELECT pg_catalog.lowrite(0, '\x7171776471776471647764776564776564776564');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17324', 131072);
SELECT pg_catalog.lowrite(0, '\x777164716471647177647771647177');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17325', 131072);
SELECT pg_catalog.lowrite(0, '\x7771647177647177647177647177647177647177647771647177647177647177647771');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17326', 131072);
SELECT pg_catalog.lowrite(0, '\x7765396277656266c4b17565776266c4b1757765c4b17566627765c4b1756266c4b17577656266c4b175627765c4b17566627765c4b175666277c4b17565626675c4b16577626675c4b1776575c4b1666277656662c4b1757765626675c4b177656266c4b175627765c4b17566627765c4b1756266c4b17565776662c4b17577656266c4b17565776266c4b17577626566c4b175776265c4b175666277c4b175666277');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17327', 131072);
SELECT pg_catalog.lowrite(0, '\x616161616161616c646d77656f646f776e646fc4b16e77656e646e6577c4b1646ec4b177656e646e7765646f6ec4b16f77656e64c4b16e7765646fc4b16e646fc4b16e7765646ec4b1656f776e64c4b16f65776e64c4b16f65776e64c4b16f656e77646fc4b16e7765646fc4b16e646fc4b16e65776fc4b1646e6fc4b177656e64c4b16f6e646e7765c4b16f646e7765c4b16f6e646fc4b177656e646f77656f64c4b177656fc4b1646e7765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17328', 131072);
SELECT pg_catalog.lowrite(0, '\x71777764776566717764667177647177647771647771');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17329', 131072);
SELECT pg_catalog.lowrite(0, '\x647771646d646c77716d646c77646d6c776d64776d646c6d776c646d6c776d646c6d776d646d776c646d77646c6d77');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17355', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d2047616d696e67204665737420323032352c20332067c3bc6e20626f79756e63612031302e303030272764656e2066617a6c61206b6174c4b16cc4b16d63c4b179c4b12061c49fc4b1726c6164c4b12e205965726c69206f79756e2067656c69c59f7469726963696c65722c20652d73706f722074616bc4b16d6c6172c4b12076652074656b6e6f6c6f6a69206d61726b616c6172c4b12061796ec4b120c3a76174c4b120616c74c4b16e64612062756c75c59f74752e205a697961726574c3a7696c6572207475726e7576616c617261206b6174c4b16c64c4b12c2073656d696e65726c657264652073656b74c3b672206c696465726c6572696e692064696e6c6564692076652056522064656e6579696d20616c616e6c6172c4b16e6461206b657969666c6920616e6c6172207961c59f6164c4b12e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17356', 131072);
SELECT pg_catalog.lowrite(0, '\x546563682053756d6d6974204b6f6e796120323032352c2079617ac4b16cc4b16d2c207961706179207a656b612076652073696265722067c3bc76656e6c696b2074656d616c6172c4b1796c612064c3bc7a656e6c656e64692e2045746b696e6c696b7465203530e2809964656e2066617a6c61206b6f6e75c59f6d6163c4b12079657220616c64c4b12e2047656c69c59f7469726963696c65722079656e69207472656e646c65726920c3b6c49f72656e64692c206e6574776f726b696e67206f747572756d6c6172c4b16e64612070726f6a656c6572696e692074616ec4b17474c4b12e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17357', 131072);
SELECT pg_catalog.lowrite(0, '\x53746172745570204d65657420323032352065746b696e6c69c49f696e6465203330e2809964616e2066617a6c612067697269c59f696d20796174c4b172c4b16d63c4b16c6172612070726f6a656c6572696e692073756e64752e2041494d4167656e63792c2067697269c59f696d63696c657265206d656e746f726c756b206465737465c49f69207361c49f6c6164c4b120766520656e2069796920332070726f6a6520c3b664c3bc6c6c656e646972696c64692e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17358', 131072);
SELECT pg_catalog.lowrite(0, '\x4b6f6e79612054656b6e6f6b656e74e2809974652079657220616c616e2079656e69206f666973696d697a2c206d6f6465726e20616c74796170c4b173c4b12076652067656e69c59f20c3a7616cc4b1c59f6d6120616c616ec4b1796c6120656b6962696d697a652064616861206b6f6e666f726c7520626972206f7274616d2073756e75796f722e2041c3a7c4b16cc4b1c59f2065746b696e6c69c49f696e6465206dc3bcc59f746572696c6572696d697a2076652069c59f206f7274616b6c6172c4b16dc4b17a2064612079657220616c64c4b12e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17359', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d41636164656d79207461726166c4b16e64616e2064c3bc7a656e6c656e656e2079617a20626f6f7463616d70e280997465206b6174c4b16cc4b16d63c4b16c61722052656163742c20537072696e6720426f6f7420766520506f737467726553514c2074656b6e6f6c6f6a696c6572696e6920c3b6c49f72656e6563656b2e20342068616674612073c3bc726563656b2065c49f6974696d20736f6e756e6461206261c59f6172c4b16cc4b1206b6174c4b16cc4b16d63c4b16c61722069c59f6520616cc4b16d2073c3bc726563696e6520646168696c206564696c6563656b2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17360', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d4167656e6379e280996e696e2064657374656b6c656469c49f69204861636b6174686f6e20323032352065746b696e6c69c49f6920313030206b6174c4b16cc4b16d63c4b1796c6120676572c3a7656b6c65c59f746972696c64692e204b617a616e616e20656b69702c20616bc4b16c6cc4b120c59f6568697220757967756c616d616c6172c4b120c3bc7a6572696e652067656c69c59f7469726469c49f692070726f6a65796c652062c3bc79c3bc6b20c3b664c3bc6cc3bc20616c64c4b12e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17361', 131072);
SELECT pg_catalog.lowrite(0, '\x41494d4167656e63792c20476f6f676c6520436c6f756420506172746e65722070726f6772616dc4b16e61206b6174c4b16c6172616b2054c3bc726b697965e2809964656b692069c59f6c65746d656c6572652062756c75742074656b6e6f6c6f6a696c6572692c207961706179207a656b6120c3a7c3b67ac3bc6d6c6572692076652064696a6974616c2064c3b66ec3bcc59fc3bc6d2064616ec4b1c59f6d616e6cc4b1c49fc4b12068697a6d65746c6572692073756e6163616b2e20c59e69726b65742c2062752069c59f206269726c69c49f69796c65206dc3bcc59f746572696c6572696e6520646168612067c3bc76656e696c69722076652079656e696c696bc3a76920c3a7c3b67ac3bc6d6c6572207361c49f6c616d6179c4b12068656465666c69796f722e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17362', 131072);
SELECT pg_catalog.lowrite(0, '\x323032352079c4b16cc4b1207374726174656a697369206b617073616dc4b16e64612041494d4167656e63792c20416d7374657264616de2809964612079656e6920626972206f6669732061c3a7616361c49fc4b16ec4b120647579757264752e20417672757061206f7065726173796f6e6c6172c4b1796c61206269726c696b746520c59f69726b65742c20756c75736c617261726173c4b12070726f6a656c657264652079657220616c6172616b2054c3bc726b2079617ac4b16cc4b16d2069687261636174c4b16e61206b61746bc4b1207361c49f6c616d6179c4b120706c616e6cc4b1796f722e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17363', 131072);
SELECT pg_catalog.lowrite(0, '\x42756c75742073697374656d6c657269796c6520757967756c616d616c6172c4b16ec4b17ac4b120c3b66cc3a7656b6c656e6562696c69722068616c6520676574697269796f72757a2e2053756e7563752079c3b66e6574696d692c20796564656b6c656d65207665206d616c69796574206f7074696d697a6173796f6e7520c3a7c3b67ac3bc6d6c6572692073756e75796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17364', 131072);
SELECT pg_catalog.lowrite(0, '\x55492f5558207461736172c4b16d20656b6962696d697a2c206b756c6c616ec4b163c4b12064656e6579696d696e692076652067c3b67273656c20657374657469c49f69206269726c65c59f7469726572656b20c3bc72c3bc6e6c6572696e697a6920c3b66e20706c616e6120c3a7c4b16b6172c4b1722e204669676d612c2041646f6265205844206769626920617261c3a76c61726c612070726f746f7469706c656d6520766520746573742073c3bc7265c3a76c6572696e692079c3b66e657469796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17365', 131072);
SELECT pg_catalog.lowrite(0, '\x5961706179207a656b61206d6f64656c6c657269796c652069c59f2073c3bc7265c3a76c6572696e697a692068c4b17a6c616e64c4b172c4b1796f72757a2e2047c3b672c3bc6e74c3bc2069c59f6c656d652c20646fc49f616c2064696c2069c59f6c656d6520284e4c5029207665207461686d696e2073697374656d6c657269206769626920616c616e6c6172646120c3b67a656c20c3a7c3b67ac3bc6d6c65722067656c69c59f74697269796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17366', 131072);
SELECT pg_catalog.lowrite(0, '\x4d6f62696c20757967756c616d612067656c69c59f7469726d6520656b6962696d697a2c206b756c6c616ec4b163c4b12064656e6579696d696e6920c3b66e20706c616e6461207475746172616b20466c75747465722c205265616374204e6174697665207665204b6f746c696e20676962692074656b6e6f6c6f6a696c65726c6520c3b66cc3a7656b6c656e6562696c697220757967756c616d616c61722067656c69c59f74697269722e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17367', 131072);
SELECT pg_catalog.lowrite(0, '\x64656577646577646577647765647765647765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17368', 131072);
SELECT pg_catalog.lowrite(0, '\x64656577646577646577647765647765647765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17369', 131072);
SELECT pg_catalog.lowrite(0, '\x64656577646577646577647765647765647765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17370', 131072);
SELECT pg_catalog.lowrite(0, '\x64656577646577646577647765647765647765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17371', 131072);
SELECT pg_catalog.lowrite(0, '\x64656577646577646577647765647765647765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17381', 131072);
SELECT pg_catalog.lowrite(0, '\x64656577646577646577647765647765647765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17382', 131072);
SELECT pg_catalog.lowrite(0, '\x64656577646577646577647765647765647765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17383', 131072);
SELECT pg_catalog.lowrite(0, '\x64656577646577646577647765647765647765');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17384', 131072);
SELECT pg_catalog.lowrite(0, '\x666c343320666c6b33346c6b662033346c2066');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17385', 131072);
SELECT pg_catalog.lowrite(0, '\x42756c75742073697374656d6c657269796c6520757967756c616d616c6172c4b16ec4b17ac4b120c3b66cc3a7656b6c656e6562696c69722068616c6520676574697269796f72757a2e2053756e7563752079c3b66e6574696d692c20796564656b6c656d65207665206d616c69796574206f7074696d697a6173796f6e7520c3a7c3b67ac3bc6d6c6572692073756e75796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17386', 131072);
SELECT pg_catalog.lowrite(0, '\x42756c75742073697374656d6c657269796c6520757967756c616d616c6172c4b16ec4b17ac4b120c3b66cc3a7656b6c656e6562696c69722068616c6520676574697269796f72757a2e2053756e7563752079c3b66e6574696d692c20796564656b6c656d65207665206d616c69796574206f7074696d697a6173796f6e7520c3a7c3b67ac3bc6d6c6572692073756e75796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17387', 131072);
SELECT pg_catalog.lowrite(0, '\x55492f5558207461736172c4b16d20656b6962696d697a2c206b756c6c616ec4b163c4b12064656e6579696d696e692076652067c3b67273656c20657374657469c49f69206269726c65c59f7469726572656b20c3bc72c3bc6e6c6572696e697a6920c3b66e20706c616e6120c3a7c4b16b6172c4b1722e204669676d612c2041646f6265205844206769626920617261c3a76c61726c612070726f746f7469706c656d6520766520746573742073c3bc7265c3a76c6572696e692079c3b66e657469796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17388', 131072);
SELECT pg_catalog.lowrite(0, '\x5961706179207a656b61206d6f64656c6c657269796c652069c59f2073c3bc7265c3a76c6572696e697a692068c4b17a6c616e64c4b172c4b1796f72757a2e2047c3b672c3bc6e74c3bc2069c59f6c656d652c20646fc49f616c2064696c2069c59f6c656d6520284e4c5029207665207461686d696e2073697374656d6c657269206769626920616c616e6c6172646120c3b67a656c20c3a7c3b67ac3bc6d6c65722067656c69c59f74697269796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17389', 131072);
SELECT pg_catalog.lowrite(0, '\x4d6f62696c20757967756c616d612067656c69c59f7469726d6520656b6962696d697a2c206b756c6c616ec4b163c4b12064656e6579696d696e6920c3b66e20706c616e6461207475746172616b20466c75747465722c205265616374204e6174697665207665204b6f746c696e20676962692074656b6e6f6c6f6a696c65726c6520c3b66cc3a7656b6c656e6562696c697220757967756c616d616c61722067656c69c59f74697269722e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17412', 131072);
SELECT pg_catalog.lowrite(0, '\x323032352079c4b16cc4b1207374726174656a697369206b617073616dc4b16e64612041494d4167656e63792c20416d7374657264616de2809964612079656e6920626972206f6669732061c3a7616361c49fc4b16ec4b120647579757264752e20417672757061206f7065726173796f6e6c6172c4b1796c61206269726c696b746520c59f69726b65742c20756c75736c617261726173c4b12070726f6a656c657264652079657220616c6172616b2054c3bc726b2079617ac4b16cc4b16d2069687261636174c4b16e61206b61746bc4b1207361c49f6c616d6179c4b120706c616e6cc4b1796f722e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17462', 131072);
SELECT pg_catalog.lowrite(0, '\x5765206d616e6167652070726f66657373696f6e616c206573706f727473207465616d732c20746f75726e616d656e74732c20616e6420636f6d6d756e697479206576656e74732e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17496', 131072);
SELECT pg_catalog.lowrite(0, '\x5961706179207a656b61206d6f64656c6c657269796c652069c59f2073c3bc7265c3a76c6572696e697a692068c4b17a6c616e64c4b172c4b1796f72757a2e2047c3b672c3bc6e74c3bc2069c59f6c656d652c20646fc49f616c2064696c2069c59f6c656d6520284e4c5029207665207461686d696e2073697374656d6c657269206769626920616c616e6c6172646120c3b67a656c20c3a7c3b67ac3bc6d6c65722067656c69c59f74697269796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17497', 131072);
SELECT pg_catalog.lowrite(0, '\x5961706179207a656b61206d6f64656c6c657269796c652069c59f2073c3bc7265c3a76c6572696e697a692068c4b17a6c616e64c4b172c4b1796f72757a2e2047c3b672c3bc6e74c3bc2069c59f6c656d652c20646fc49f616c2064696c2069c59f6c656d6520284e4c5029207665207461686d696e2073697374656d6c657269206769626920616c616e6c6172646120c3b67a656c20c3a7c3b67ac3bc6d6c65722067656c69c59f74697269796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17498', 131072);
SELECT pg_catalog.lowrite(0, '\x5961706179207a656b61206d6f64656c6c657269796c652069c59f2073c3bc7265c3a76c6572696e697a692068c4b17a6c616e64c4b172c4b1796f72757a2e2047c3b672c3bc6e74c3bc2069c59f6c656d652c20646fc49f616c2064696c2069c59f6c656d6520284e4c5029207665207461686d696e2073697374656d6c657269206769626920616c616e6c6172646120c3b67a656c20c3a7c3b67ac3bc6d6c65722067656c69c59f74697269796f72757a2e');
SELECT pg_catalog.lo_close(0);

SELECT pg_catalog.lo_open('17524', 131072);
SELECT pg_catalog.lowrite(0, '\x5961706179207a656b61206d6f64656c6c657269796c652069c59f2073c3bc7265c3a76c6572696e697a692068c4b17a6c616e64c4b172c4b1796f72757a2e2047c3b672c3bc6e74c3bc2069c59f6c656d652c20646fc49f616c2064696c2069c59f6c656d6520284e4c5029207665207461686d696e2073697374656d6c657269206769626920616c616e6c6172646120c3b67a656c20c3a7c3b67ac3bc6d6c65722067656c69c59f74697269796f72757a2e');
SELECT pg_catalog.lo_close(0);

COMMIT;

--
-- Name: alt_servisler alt_servisler_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alt_servisler
    ADD CONSTRAINT alt_servisler_pkey PRIMARY KEY (id);


--
-- Name: ayarlar ayarlar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ayarlar
    ADD CONSTRAINT ayarlar_pkey PRIMARY KEY (id);


--
-- Name: crew crew_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.crew
    ADD CONSTRAINT crew_pkey PRIMARY KEY (id);


--
-- Name: esports esports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.esports
    ADD CONSTRAINT esports_pkey PRIMARY KEY (id);


--
-- Name: etkinlikler etkinlikler_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.etkinlikler
    ADD CONSTRAINT etkinlikler_pkey PRIMARY KEY (id);


--
-- Name: haberler haberler_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.haberler
    ADD CONSTRAINT haberler_pkey PRIMARY KEY (id);


--
-- Name: influencers influencers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.influencers
    ADD CONSTRAINT influencers_pkey PRIMARY KEY (id);


--
-- Name: kullanicilar kullanicilar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kullanicilar
    ADD CONSTRAINT kullanicilar_pkey PRIMARY KEY (id);


--
-- Name: media media_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


--
-- Name: media_thumbnails media_thumbnails_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media_thumbnails
    ADD CONSTRAINT media_thumbnails_pkey PRIMARY KEY (id);


--
-- Name: portfolio_images portfolio_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio_images
    ADD CONSTRAINT portfolio_images_pkey PRIMARY KEY (id);


--
-- Name: portfolio portfolio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio
    ADD CONSTRAINT portfolio_pkey PRIMARY KEY (id);


--
-- Name: servisler servisler_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.servisler
    ADD CONSTRAINT servisler_pkey PRIMARY KEY (id);


--
-- Name: shoots shoots_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shoots
    ADD CONSTRAINT shoots_pkey PRIMARY KEY (id);


--
-- Name: sponsorlar sponsorlar_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sponsorlar
    ADD CONSTRAINT sponsorlar_pkey PRIMARY KEY (id);


--
-- Name: videos videos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.videos
    ADD CONSTRAINT videos_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict oux2dAQ2dnQdN0zjz5MtbHye3bcUDIKBhfzoLCRxdkZxH6J3ZnGo1HdLwqv6lfO

